### PR TITLE
Ensure TOTP value counter is ticking after defining OTP

### LINKED ISSUE #192: TOTP value counter not ticking
If you define OTP for an existing entry, the TOTP column displays the TOTP as well as the counter (remaining time) as expected.

Unfortunately the counter is not ticking right away. To achieve this, you have to select a different group and reselect the original group

### PR DESCRIPTION
**Pull request by Rookiestyle**
Fixes #192 

Changes in `OnTimerTick` and `UIStateUpdated` are not required for the fix to work, nevertheles I think they should be added for performance reasons
- Read entries of subgroups only if entries of subgroups are displayed as well
- Stop looking for valid OTP settings after the first hit

### CODE REVIEW

**Comment by Rookiestyle** [comment]
I assume SonarCloud failed because of insufficient comments?

If additional comments or something else is required, just let me know.

**Comment by dannoe** [comment]
Thanks for your contribution. I will look into it.
SonarCloud has failed because it expects at least the same test coverage for new pull requests.

**Comment by dannoe** [comment]
I tried to create some "good" tests, but it's very difficult for such UI- and KeePass-dependent code.
LGTM.

**Review by dannoe — APPROVED** [review]

**Comment by robinvanpoppel** [comment]
I'm also ok with this not being fully tested. Looks good. Thanks @Rookiestyle and @dannoe!

**Pull request merged**
