### PR TITLE
[Enhancement] add Plugin 📦 Installation & Upgrade info to readme

### PR DESCRIPTION
**Pull request by 4-FLOSS-Free-Libre-Open-Source-Software**

### CODE REVIEW

**Comment by robinvanpoppel** [comment]
Hi Bernd, 

Thanks for improving the documentation. I was not aware a community choco package existed! Are you maintaining it? And does it make sense to automate the choco package creation?

Kind regards,
Robin

**Review by robinvanpoppel — APPROVED** [review]

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Hi Robin,

 

thanks for the Plugin.

 

> Are you maintaining it? 

 

I'm not the maintainer, current maintainer seems to be: [Pauby](https://community.chocolatey.org/profiles/Pauby)

 

> And does it make sense to automate the choco package creation?

 

Depends, I see last update dates 12 Sep 2020. So there isn't such frequent updates needed to create anyway? 

 

Regards

**Comment by pauby** [comment]
@robinvanpoppel The package is automatically updated upon a new GitHub release.

**Comment by robinvanpoppel** [comment]
Awesome @pauby !

**Pull request merged**
