### PR TITLE
Add a TOTP Status Column

### PR DESCRIPTION
**Pull request by robinvanpoppel**
This column shows whether the column has (valid) settings to calculate a TOTP.
Double clicking the column copies the current TOTP if that is enabled in the settings (just like the TOTP column).
This partly solves #120

**Column selection:**
image

**Column in the main window**
image

### CODE REVIEW

**Comment by dannoe** [comment]
Wouldn't it be better to copy the current TOTP value when double-clicking an entry that is already set up?

**Comment by robinvanpoppel** [comment]
That makes sense to me as well. I'll change that 👍

**Comment by robinvanpoppel** [comment]
@dannoe, I've pushed some changes and edited the first message, indicating how the double click behavior works.

**Comment by robinvanpoppel** [comment]
That's best of both worlds indeed. I've added an extra method on the plugin to see if a TOTP code can be generated. If we can generate TOTP for the entry it is copied if you have the setting enabled, otherwise the setup dialog will popup.

**Pull request merged**
